version: '3.8'

services:
  tts-api:
    build: .
    container_name: tts-api-service
    ports:
      - "5000:5000"
    volumes:
      - ./temp_f5:/app/temp_f5
      - ./hf_cache:/root/.cache/huggingface   # cache model ไว้ ไม่ต้องโหลดซ้ำทุก restart
    restart: unless-stopped
